const staticData = {

    iconsList : {
        //for user
        username:'fas fa-user',
        password:'fas fa-key',
        'repeat-password':'fas fa-key',
        'full-name':'fas fa-user',
        email:'fas fa-envelope',
        phone:'fas fa-phone',
        //for dogs
        name:'fas fa-dog',
        breed:'',
        age:'fas fa-paw',
        'image-url':'fas fa-camera',
        status:'',
        story:'fas fa-feather'
    },

    errorMassages : {
        //for user
        username:'User name must be 3 to 15 symbols',
        password:'Password must be 5 to 10 symbols',
        'repeat-password':'Passwords should match',
        'full-name':'Full name must be 5 to 25 symbols',
        email:'Please provide a valid email',
        phone:'Please provide a valid phone number',
        //for dogs
        name:'Name must be 2 to 10 symbols',
        breed:'Breed field is required',
        age:'Age must be a number from 0 to 15',
        'image-url':'Please provide a valid URL',
        status:'Status field is required',
        story:'Story must up to symbols'
    },
    statuses:[
        'available',
        'processing',
        'adopted'
    ],

    dashboardColumns:[
        '#',
        'Dog ID',
        'User ID',
        'Status',
        'Update',
    ],
    breeds :[        
        "affenpinscher",
        "african",
        "airedale",
        "akita",
        "appenzeller",
        "basenji",
        "beagle",
        "bluetick",
        "borzoi",
        "bouvier",
        "boxer",
        "brabancon",
        "briard",
        "bulldog",
        "bullterrier",
        "cairn",
        "cattledog",
        "chihuahua",
        "chow",
        "clumber",
        "cockapoo",
        "collie",
        "coonhound",
        "corgi",
        "cotondetulear",
        "dachshund",
        "dalmatian",
        "dane",
        "deerhound",
        "dhole",
        "dingo",
        "doberman",
        "elkhound",
        "entlebucher",
        "eskimo",
        "frise",
        "germanshepherd",
        "greyhound",
        "groenendael",
        "hound",
        "husky",
        "keeshond",
        "kelpie",
        "komondor",
        "kuvasz",
        "labrador",
        "leonberg",
        "lhasa",
        "malamute",
        "malinois",
        "maltese",
        "mastiff",
        "mexicanhairless",
        "mix",
        "mountain",
        "newfoundland",
        "otterhound",
        "papillon",
        "pekinese",
        "pembroke",
        "pinscher",
        "pointer",
        "pomeranian",
        "poodle",
        "pug",
        "puggle",
        "pyrenees",
        "redbone",
        "retriever",
        "ridgeback",
        "rottweiler",
        "saluki",
        "samoyed",
        "schipperke",
        "schnauzer",
        "setter",
        "sheepdog",
        "shiba",
        "shihtzu",
        "spaniel",
        "springer",
        "stbernard",
        "terrier",
        "vizsla",
        "weimaraner",
        "whippet",
        "wolfhound"
    ],

}

export default staticData;